# render.yaml - Render configuration file
services:
  - type: web
    name: resume-optimizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
    disk:
      name: resume-optimizer-disk
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1
